package chapter2;

public class FormatOutputDriver {
    public static void main(String[] args) {

        //============================================================================//
        // Chapter 2 - Checkpoint Exercises
        //============================================================================//

        FormatOutput obj0 = new FormatOutput();

        //set the value inside aDouble.
        obj0.setaDouble(1234567.456);

        //print out the value of aDouble delimited with commas and rounded to 2 decimal places.
        System.out.printf("%,.2f\n", obj0.getaDouble());
        //doing the exact same thing with a static method from FormatOutput class
        FormatOutput.formatDouble0(obj0.getaDouble());

        System.out.println();

        //change the value inside aDouble.
        obj0.setaDouble(123.456);

        //print out the value of aDouble within 10 spaces rounded to 1 decimal space.
        System.out.printf("%10.1f\n", obj0.getaDouble());
        //doing the exact same thing with a static method from FormatOutput class
        FormatOutput.formatDouble1(obj0.getaDouble());

        System.out.println();

        //print out the value of aDouble within 8 spaces padded by '0'.
        System.out.printf("%08.1f\n", obj0.getaDouble());
        //doing the exact same thing with a static method from FormatOutput class
        FormatOutput.formatDouble2(obj0.getaDouble());

        System.out.println();

        obj0.setAnInt(123456);

        //print out the value of anInt delimited by commas in a field of 10 spaces.
        System.out.printf("%,10d\n", obj0.getAnInt());
        //doing the exact same thing with a static method from FormatOutput class
        FormatOutput.formatInteger(obj0.getAnInt());

        System.out.println();

        obj0.setaDouble(123456.789);

        //print out the value of aDouble in 20 spaces delimited by commas, rounded to 2 decimal places.
        System.out.printf("%,20.2f\n", obj0.getaDouble());
        //doing the exact same thing with a static method from FormatOutput class
        FormatOutput.formatDouble3(obj0.getaDouble());

        System.out.println();

        obj0.setaString("James");

        //print out the contents of aString in a field of 20 spaces.
        System.out.println(String.format("%20s", obj0.getaString()));
        //doing the exact same thing with a static method from FormatOutput class
        FormatOutput.formatString(obj0.getaString());

        System.out.println();

        //============================================================================//
        // Chapter 2 - Review / Programming Challenges
        //============================================================================//

        FormatOutput.printStars();
        System.out.println();

        //#5. Cookie Calories
        //This static method will receive an integer.
        //The integer will represent the amount of cookies the user has consumed.
        //It will return the amount of calories consumed.
        System.out.println("You have consumed "+
                FormatOutput.cookiesConsumed(1) +
                " calories.");
        System.out.println();

        //#6. Sales Prediction
        //This static method receives a double.
        //The double represents the total sales of the company
        //65% of the total sales are returned
        System.out.println("The amount of sales generated by the East Coast"+
                " sales division = $" +
                FormatOutput.salesPrediction(8300000.00));
        System.out.println();

        //#7. Land Calculation
        //The double passed to this method represents the amount of square feet
        //The method returns the square footage converted to acres.
        System.out.println("There are "+
                FormatOutput.howManyAcres(389767)+
                " acres in "+ 389767 + " square feet.");
        System.out.println();

        //#8. Sales Tax
        //Pass a double representing a purchase price to the method.
        //The method will print out the State tax, County tax and transaction total.
        FormatOutput.enterSalePrice(100);
        System.out.println("\n");


        //9. Miles-Per-Gallon
        //Pass the amount of miles driven as the first argument in the method
        //Then pass the amount of gallons consumed to the second argument in the method.
        System.out.printf("Your car drove %.2f miles for every 1 gallon of gas,",
                FormatOutput.milesPerGallon(100, 5));
        System.out.println();

        //10. Test Average
        //This method call requires interaction from the user.
        //It has been commented out for the time being.
        //Feel free to experiment with it.

        /*
        System.out.printf("The average of the three test scores = %.2f",
                FormatOutput.averageOfThreeScores());
        */

        System.out.println();

        //#11. Male and Female Percentages
        //This method requires user interaction.
        //It has been commented out for the time being.
        //Feel free to play with it.
        /*
        FormatOutput.genderPercentage();

         */

        System.out.println();

        //#12. Manipulate String
        //This method requires user input
        //It has been commented out for the time being.
        /*
        FormatOutput.manipulateString();

         */

        System.out.println();

        //#13. Restaurant Bill
        //This method requires user input
        //It has been commented out for the time being.
        /*
        FormatOutput.taxAndTip();

         */

        System.out.println();

        //#14. Stock Commission

        //Pass the number of shares and the price per share to the method.
        FormatOutput.stockCommission(10, 1.25);
        System.out.println();

        //#15. Ingredient Adjuster.

        //Pass the amount of cookies you want to bake to the method.
        FormatOutput.cookieAdjuster(24);

        //#16. Energy Drink Consumption

        //Calling this static method will print out -
        //the amount of customers  who purchase one or more energy drinks per week.
        //the amount who prefer citrus-flavored energy drinks from the first amount.
        FormatOutput.consumerPercenage();
        System.out.println();

        //#17. Word Game
        //Calling this method will run a word game for the user.
        //System.out.println(FormatOutput.wordGame());

        //#18. Stock Transaction Program
        FormatOutput.stockProgram();

        //#19. Planting Grapevines
        //FormatOutput.grapeVines();

        //#20. Compound Interest
        FormatOutput.compoundInterest();

        //After having used JOptionPane, it is good practice to terminate the program
        // with System.exit(0).
        //This will ensure that the JVM exits and any remaining threads are killed.
        JOptionPaneClass terminatingProgramAfterUsingJOptionPane = new JOptionPaneClass();
        terminatingProgramAfterUsingJOptionPane.terminateProgram();
    }
}
